/*eslint max-len:0*/
define({
  AUTHOR: 'Author',
  CANCEL: 'Cancel',
  CLOSE: 'Close',
  CLOSE_AND_RELOAD_MESSAGE: 'After modifying installed extensions, Brackets will need to reload. You\'ll be prompted to save unsaved changes.',
  _DEPENDENCIES: 'dependencies',
  _DOWNLOADS: 'downloads',
  _LAST_WEEK: 'last week',
  LATEST: 'Latest',
  INSTALL: 'Install',
  INSTALLED: 'Installed',
  OK: 'OK',
  _ON_GITHUB: 'on GitHub',
  _OPEN_ISSUES: 'open issues',
  _OPEN_PULLS: 'open pull requests',
  OPERATION_IN_PROGRESS: 'Operation in progress\u2026',
  REGISTRY_DIALOG_TITLE: 'brackets-npm-registry',
  REINSTALL: 'Reinstall',
  REMOVE: 'Remove',
  RELOAD: 'Reload',
  SET_NODE_PATH: 'Set node path',
  SET_NODE_PATH_QUESTION: 'Please enter the absolute path to your node executable',
  _SHOW_LINK: 'show\u2026',
  _TOTAL: 'total',
  UPDATE: 'Update'
});
